/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Examen2Progra2_FavioNataren_22141210;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author favio
 */
public class Main extends javax.swing.JFrame {

    
    ArrayList<String> S = new ArrayList();
    Manejo_de_datos mc = new Manejo_de_datos("./cientificos.cbm");
    Manejo_de_datos mc2 = new Manejo_de_datos("./planetas.cbm");

    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        mc.cargarArchivo();
        boxllen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menusito = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        barrita = new javax.swing.JProgressBar();
        jRadioButton1 = new javax.swing.JRadioButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cosa2 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        cosa1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        treeplanet = new javax.swing.JTree();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cienti = new javax.swing.JComboBox<>();
        nombre = new javax.swing.JTextField();

        jMenuItem1.setText("Planeta 1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menusito.add(jMenuItem1);
        menusito.add(jSeparator1);

        jMenuItem2.setText("Planeta 2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menusito.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barrita.setStringPainted(true);
        jPanel2.add(barrita, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 26, 580, 60));

        jRadioButton1.setBackground(new java.awt.Color(102, 102, 102));
        jRadioButton1.setText("Publicos");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 100, 30));

        jToggleButton1.setBackground(new java.awt.Color(153, 153, 153));
        jToggleButton1.setText("Añadir Cientifico");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        cosa2.setEditable(false);
        cosa2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(cosa2);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 270, 30));

        cosa1.setEditable(false);
        cosa1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(cosa1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 270, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Colisionar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 270, 60));

        treeplanet.setBackground(new java.awt.Color(102, 102, 102));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        treeplanet.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeplanet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeplanetMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(treeplanet);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 270, 270));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cientificos");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        cienti.setBackground(new java.awt.Color(153, 153, 153));
        cienti.setOpaque(false);
        cienti.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cientiItemStateChanged(evt);
            }
        });
        jPanel2.add(cienti, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 260, 30));

        nombre.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 270, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(461, 461, 461))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            mc.cargarArchivo();

            planetas plnettt1 = null;
            planetas plnettt2 = null;
            for (planetas plat : mc.getCienti().get(cienti.getSelectedIndex()).getPla()) {
                if (cosa1.getText().equals(plat.getNombre())) {
                    plnettt1 = plat;
                }
                if (cosa2.getText().equals(plat.getNombre())) {
                    plnettt2 = plat;
                }
            }
            if (plnettt1 == null||plnettt2 == null) {
                mc2.cargarArchivo();
                for (planetas plat : mc2.getPla()) {
                    if (cosa1.getText().equals(plat.getNombre())) {
                        plnettt1 = plat;
                    }
                    if (cosa2.getText().equals(plat.getNombre())) {
                        plnettt2 = plat;
                    }
                }
            }
            Random r = new Random();
            boolean pass = false;
            int ramdom = 1 + r.nextInt(100);
            if (ramdom <= 25) {
                pass = true;
            }
            double X = (Math.pow((plnettt1.getX() - plnettt2.getX()), 2));
            double Y = Math.pow(plnettt1.getY() - plnettt2.getY(), 2);
            double d = Math.sqrt(X + Y);
            if (pass) {
                mc.cargarArchivo();
                mc.getCienti().get(cienti.getSelectedIndex()).setPla(new planetas((plnettt1.getTamanio() + plnettt2.getTamanio()) / 2, (plnettt1.getTamanio() + plnettt2.getTamanio()) / 2, JOptionPane.showInputDialog(this, "Ingrese Nuevo Nombre Del Planeta Creado"), (plnettt1.getX() + plnettt2.getX()) / 2, (plnettt1.getY() + plnettt2.getY()) / 2));
                mc.escribirArchivo();
            }


            int val = (int) d;
            barrita.setMaximum(val);
            hilo h = new hilo(barrita, val);
            Thread HILO = new Thread(h);
            HILO.start();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Asegurese de ingresedo 2 planetas!");
        }


    }//GEN-LAST:event_jButton1MouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        if (jRadioButton1.isSelected()) {
            cienti.setEnabled(false);
            mc2.cargarArchivopublicos();
            S = new ArrayList();
            DefaultTreeModel modelo1 = (DefaultTreeModel) treeplanet.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo1.getRoot();
            root = new DefaultMutableTreeNode("Planetas");
            for (planetas planetass : mc2.getPla()) {
                S.add(planetass.getNombre());
                DefaultMutableTreeNode planetitas = new DefaultMutableTreeNode(planetass.getNombre());
                root.add(planetitas);
            }
            modelo1.setRoot(root);
        } else {
            try {
                mc.cargarArchivo();
                cienti.setEnabled(true);
                S = new ArrayList();
                DefaultTreeModel modelo1 = (DefaultTreeModel) treeplanet.getModel();
                DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo1.getRoot();
                root = new DefaultMutableTreeNode("Planetas descubiertos por " + cienti.getSelectedItem());
                for (planetas planetass : mc.getCienti().get(cienti.getSelectedIndex()).getPla()) {
                    DefaultMutableTreeNode planetitas = new DefaultMutableTreeNode(planetass.getNombre());
                    root.add(planetitas);
                    S.add(planetass.getNombre());
                }
                modelo1.setRoot(root);
                cosa1.setText("");
                cosa2.setText("");
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        mc.cargarArchivo();
        mc.setCienti(new cientificos(nombre.getText()));
        mc.escribirArchivo();
        boxllen();
        nombre.setText("");
        JOptionPane.showMessageDialog(this, "El Cientifico se agrego correctamente");
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void cientiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cientiItemStateChanged
        try {
            cienti.setEnabled(true);
            S = new ArrayList();
            mc.cargarArchivo();
            DefaultTreeModel modelo1 = (DefaultTreeModel) treeplanet.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo1.getRoot();
            root = new DefaultMutableTreeNode("Planetas descubiertos por " + cienti.getSelectedItem());
            for (planetas planetass : mc.getCienti().get(cienti.getSelectedIndex()).getPla()) {
                DefaultMutableTreeNode planetitas = new DefaultMutableTreeNode(planetass.getNombre());
                root.add(planetitas);
                S.add(planetass.getNombre());
            }
            modelo1.setRoot(root);
            cosa1.setText("");
            cosa2.setText("");
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cientiItemStateChanged

    private void treeplanetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeplanetMouseClicked
        if (evt.isMetaDown()) {
            menusito.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_treeplanetMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            int[] r = treeplanet.getSelectionRows();
            cosa1.setText(S.get(r[0] - 1));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecione un valor");
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            int[] r = treeplanet.getSelectionRows();
            cosa2.setText(S.get(r[0] - 1));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecione un valor");
        }
            
        

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void boxllen() {
        cienti.removeAllItems();
        mc.cargarArchivo();
        for (cientificos cintificossss : mc.getCienti()) {
            cienti.addItem(cintificossss.getNombre());
        }

    }

    public void cintocp() {
        mc.getCienti().get(0).setPla(new terrestres(10000, 1500, "kepler-54", 340, 160));
        mc.escribirArchivo();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barrita;
    private javax.swing.JComboBox<String> cienti;
    private javax.swing.JTextPane cosa1;
    private javax.swing.JTextPane cosa2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPopupMenu menusito;
    private javax.swing.JTextField nombre;
    private javax.swing.JTree treeplanet;
    // End of variables declaration//GEN-END:variables
}
